global:
  name: train-abinet
  phase: train
  stage: train-super
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['data/scene/scene_train/'],
    batch_size: 96
  }
  test: {
    roots: ['data/scene/scene_val/'],
    batch_size: 96
  }
  data_aug: True
  multiscales: False
  num_workers: 14
  if_radical_vision_model: True

training:
  epochs: 5
  show_iters: 50
  eval_iters: 800
  save_iters: 400

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [5, 0],
    gamma: 0.1,
  }

model:
  name: 'modules.model_abinet_iter.ABINetIterModel'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: workdir/pretrain-vision-model-web-radical-samedataset/best-pretrain-vision-model.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint:  workdir/pretrain-language-model-web/best-pretrain-language-model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  language_radical: {
    checkpoint:  workdir/pretrain-language-model-web-radical/best-pretrain-radical-language-model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    loss_weight: 1.,
  }
